# Generated by Django 5.2.8 on 2026-02-23 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=10)),
                ('year', models.IntegerField()),
                ('mileage', models.PositiveIntegerField(help_text='KM Driven')),
                ('engine_capacity', models.CharField(help_text='Example: 150cc', max_length=50)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('electric', 'Electric'), ('diesel', 'Diesel')], default='petrol', max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('main_image', models.ImageField(upload_to='bike_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='bike_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='bike_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='bike_images/')),
                ('stock', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
