# Generated by Django 6.0.2 on 2026-02-23 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_alter_bike_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bike',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='image4',
        ),
        migrations.AlterField(
            model_name='bike',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='BikeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bike_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bike.bike')),
            ],
        ),
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bikes', to='bike.category'),
        ),
    ]
