# Generated by Django 6.0.2 on 2026-02-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_alter_bike_id_alter_bikeimage_id_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='BikeImage',
        ),
    ]
